version: "3.7"

networks:
  users-net:

volumes:
  postgres-data:

configs:
  nginx-conf:
    file: ./config/nginx/nginx.conf
  nginx-users:
    file: ./config/nginx/conf.d/10-api.users.local.conf
  postgres-conf:
    file: ./config/postgres/init-users-db.sh
  fluent-bit-conf:
    file: ./config/fluent-bit/fluent-bit.conf

services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
      - source: nginx-users
        target: /etc/nginx/conf.d/10-api.users.local.conf
    logging:
      driver: fluentd
      options:
        tag: docker.users.nginx
    ports:
      - 80:80
      - 90:90
    networks:
      - users-net

  user-service:
    image: systemnick/user-service:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
      - HTTP_ENDPOINT=${HTTP_ENDPOINT}
      - PGPASSWORD=${DATABASE_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: docker.users.user-service
    networks:
      - users-net

  postgres:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: postgres-conf
        target: /docker-entrypoint-initdb.d/init-users-db.sh
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: docker.users.postgres
    ports:
      - 5432:5432
    networks:
      - users-net

  # Monitoring
  cadvisor:
    image: google/cadvisor:latest
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    logging:
      driver: fluentd
      options:
        tag: docker.users.cadvisor
    ports:
      - 8080:8080
    networks:
      - users-net

  # Logging
  fluent-bit:
    image: fluent/fluent-bit:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: fluent-bit-conf
        target: /fluent-bit/etc/fluent-bit.conf
    logging:
      driver: json-file
      options:
        max-size: 500m
    ports:
      - 24224:24224
    networks:
      - users-net
